[[inputs.aos]]

  port = $INPUT_PORT_INFLUX

  # Address of the server running Telegraf, it needs to be reacheable from AOS
  address = "$LOCAL_IP"

  refresh_interval = 20

  # Streaming Type Can be "perfmon", "alerts" or "events"
  streaming_type = [ "events" ]

  # Define parameter to join the AOS Server using the REST API
  aos_server = "$AOS_SERVER"
  aos_port = $AOS_PORT
  aos_login = "$AOS_LOGIN"
  aos_password = "$AOS_PASSWORD"
