[[inputs.aos]]

  port = $INPUT_PORT_PROM

  # Address of the server running Telegraf, it's need to be reacheable from AOS
  address = "$LOCAL_IP"

  # Streaming Type Can be "perfmon", "alerts" or "events"
  streaming_type = [ "perfmon", "alerts" ]

  refresh_interval = 20

  # Define parameter to join the AOS Server using the REST API
  aos_server = "$AOS_SERVER"
  aos_port = $AOS_PORT
  aos_login = "$AOS_LOGIN"
  aos_password = "$AOS_PASSWORD"
